### ISSUE TITLE
Hardware: Add a pin header for the debug port

### ISSUE THREAD

**Issue by mgm8** [spacelab-ufsc/obdh2#100]
Now, the debug port is only available through the satellite interface connector (*P1*). A three position pin header (2,54 mm pitch) with TX, RX and GND, will make the development and tests phases easier.

Placement suggestion:
![debug-header-placement](https://user-images.githubusercontent.com/5316364/73586329-63471580-448a-11ea-944a-526e86e5670f.png)

**Comment by andrempmattos** [comment]
89e1bc8c90ebf1f832ae5d080c49557ac2904c17
c9e7176d734354e6fe43ce2643b2096f844870b2
