### ISSUE TITLE
Hardware: Remove the RS-485 transceiver and add the remaining UART port to the PC-104 bus

### ISSUE THREAD

**Issue by mgm8** [spacelab-ufsc/obdh2#148]
## PC-104 Connection

**H1-25**: UART RX (Direction = Input)
**H1-27**: UART TX (Direction = output)

> TIP: Add a 0R jumper to the TX and RX pins

**Comment by andrempmattos** [comment]
6b3e086db88b6688507596c5e7711909a50fe58a
ccb8c864bcd7d2d6ca989bbfed3b79e8cfb4af46

**Final solution:** UART in PC104 pins and RS-485 available in additional header.
