### ISSUE TITLE
Hardware: Change the position of the UART1 port in the PC-104 bus

### ISSUE THREAD

**Issue by mgm8** [spacelab-ufsc/obdh2#174]
**Remove:**
* Remove the ADD_UART0_TX signal from the H1-17
* Remove the ADD_UART0_RX signal from the H1-19

**Add:**
* Add UART1_TX signal to the H1-19 pin of the PC-104 bus
* Add UART1_RX signal to the H1-20 pin of the PC-104 bus

**Comment by andrempmattos** [comment]
**Changes performed:**
* Add UART1_TX signal to the H1-19 pin of the PC-104 bus
* Add UART1_RX signal to the H1-17 pin of the PC-104 bus
