### ISSUE TITLE
Hardware: Review the LED auxiliary resistors

### ISSUE THREAD

**Issue by andrempmattos** [spacelab-ufsc/obdh2#176]

**Comment by mgm8** [comment]
@andrempmattos can we close this issue?

**Comment by andrempmattos** [comment]
@mgm8 Yes, we can. The issue was related to removing some non-essential LEDs for a more clean board, such as: UARTs, power for every power ports. In the end, since it is already done, we can remove them in the flight model design or just not soldering.
