### ISSUE TITLE
Hardware: Remove remaining 2H header 3D bodies

### ISSUE THREAD

**Issue by andrempmattos** [spacelab-ufsc/obdh2#198]

**Comment by mgm8** [comment]
@andrempmattos can we close this issue?

**Comment by andrempmattos** [comment]
This is nether a critical or bug issue. The idea is just to remove the 2H headers 3D bodies, since they are not soldered for the flight model. Now, they appear in the 3D model as can be seen in the image below. The major concern is to cause misunderstanding with the mechanical integration responsible. At least the highest height of this connectors not overcome the standard PC-104 height. 

![image](https://user-images.githubusercontent.com/25351149/108707074-4d215280-74ee-11eb-92c2-5bfa50388703.png)
