### ISSUE TITLE
Firmware: Add the license text to the source files of the workflow scripts

### ISSUE THREAD

**Issue by mgm8** [spacelab-ufsc/obdh2#246]
All source files must have the agreement/disclaimer text of the license (as described in our [contributing guidelines)](https://github.com/spacelab-ufsc/spacelab/blob/master/CONTRIBUTING.md).

Files to fix:
* [test-workflow.yml](https://github.com/spacelab-ufsc/obdh2/blob/dev_firmware/.github/workflows/test-workflow.yml)
* [deployJSON.py](https://github.com/spacelab-ufsc/obdh2/blob/dev_firmware/.github/workflows/deployJSON.py)

Python example:
* [spacelab_decoder/bit_buffer.py](https://github.com/spacelab-ufsc/spacelab-decoder/blob/master/spacelab_decoder/bit_buffer.py)

**Comment by lzacchi** [comment]
I tried following the examples and the guidelines. If I didn't let anything go unnoticed, it should be in accordance now.
