### ISSUE TITLE
Add a FRAM or MRAM memory

### ISSUE THREAD

**Issue by mgm8** [spacelab-ufsc/obdh2#259]
Add an serial (SPI) FRAM or MRAM memory to work as a safe non-volatile memory.

**Comment by andrempmattos** [comment]
https://br.mouser.com/ProductDetail/Cypress-Semiconductor/CY15B102QN-50SXE?qs=ZSypp649SOXHRJ8%252Bksax6A%3D%3D

https://br.mouser.com/ProductDetail/Everspin-Technologies/MR20H40CDF?qs=Wndy5wu9MT%2F2g3hlaIjBag%3D%3D

**Comment by mgm8** [comment]
MR20H40CDF

Operating Supply Current: **46.5 mA** :open_mouth:

**Comment by andrempmattos** [comment]
I am probably going to use the CY15B102QN-50SXE, it is more suitable for us...
